### PR TITLE
Add explanatory text to nested-logit notebook

### PR DESCRIPTION
**Pull request by EwoutH**
Add some explanatory notes to the `01-logit-nested.ipynb` notebook. The goal hereby is to explain the concepts behind the code. Also adds a introduction, some interpretation of the results, and a summary.

I hope this is useful, please review on both correctness and readability. Please also let me know if you like this level of detail (or you would like to see more or less).

### CODE REVIEW

**Comment by EwoutH** [comment]
I just see this wasn't the first notebook in the series, but that's [`01-biogeme-basics.ipynb` ](https://github.com/U-Shift/Transport-Demand-Modelling/blob/master/Code/8.1-MultinomialLogitAndProbitModels/01-biogeme-basics.ipynb). So maybe this is a bit more detailed for this notebook. If needed I can port some changes over.

On the other hand it's the first notebook in the 8.2 series, so a bit of a recap might not be that bad.

**Comment by EwoutH** [comment]
Hi @temospena! Do you find a PR like this useful?

**Comment by EwoutH** [comment]
Hi @mncosta, @filmoura and @temospena!

In the next two weeks I will be using biogeme a lot for my master thesis, and these notebooks are really useful for that In the process I don't mind to update a few of these notebooks (it's a good way to get up to speed again since this was a few years ago), but I would need some feedback to check if I'm on the right track.

If this is not useful or not feasible that's perfectly fine, but please let me know.

**Comment by temospena** [comment]
Hi @EwoutH , thank you for these suggestions., I think they are very useful!
We should wait for the comments from @mncosta, as he is the leading author of that chapter.
ATM he's a bit busy.

**Comment by EwoutH** [comment]
Thanks for getting back! Looking forwards to his thoughts.

<hr>

> Currently researching objective and subjective cycling safety using machine learning 🚲 💻

@mncosta totally off topic, but very interesting research! I encountered [this report](https://www.kimnet.nl/publicaties/publicaties/2023/12/04/nieuwe-waarderingskengetallen-voor-reistijd-betrouwbaarheid-en-comfort) ([PDF](https://www.kimnet.nl/binaries/kimnet/documenten/publicaties/2023/12/04/nieuwe-waarderingskengetallen-voor-reistijd-betrouwbaarheid-en-comfort/Significance_Value+of+Travel+Time+in+the+Netherlands+2022_final+technical+report.pdf)) recently, it's from a Dutch consultancy institution researching value of time, commissioned by the Dutch government. One of the tings they looked at is how people value their time on different cycling infrastructure. Value of time could be used as a proxy metric for safety/comfort on certain road types. They probably have the raw data if you contact them.

Screenshot_415

**Comment by mncosta** [comment]
Hi @EwoutH , thanks for your suggestions!

Typically, these notebooks are used in class, meaning that they are followed in order and code snippets are explained in detail during class, so that's why mainly there may not be that much detail and explanations all over the chapter. However, I see that adding these can be very helpful for anyone discovering the repo and following along at a distance. So I think your additions are very valuable, and we should keep them.

Overall, everything looks great, but there is a small error that needs fixing before we merge. When you look at the model's outputs, and specifically at the pseudo R^2:
> explaining 38% of the variations in the choice outcomes, with values closer to 1 representing a perfect fit.

A Pseudo R2 of 0.38 doesn't actually mean we capture 38% of the variation in the choice outcomes. In that way, pseudo R2 cannot be really interpreted like R2 from a linear regression as it does not really capture the model's ability to predict outcomes, but rather is a way to compare models as we can analyze how much is learned vs a base model (such as a null model or ASC only model). You can take a look at _Train, K. E. (2009). Discrete choice methods with simulation. Cambridge university press._ and specifically Chapter 3.8.1. when the author talks about likelihood ratio tests. 

In sum, I think you just change that small piece of text we can merge it.

**Comment by temospena** [comment]
Thank you @mncosta !
@EwoutH can you please make that change to this branch before I merge this PR?
Thanks

**Comment by temospena** [comment]
Hi @EwoutH ! Any update regarding this minor suggestion?
Let me know so I can proceed with the merge of this PR.
Thanks

**Comment by EwoutH** [comment]
Thanks for the feedback and sorry for getting back so late. I made a change, does this describe it better/correctly?

**Pull request merged**
